from typing import Any

LIGHTS1: dict[str, Any] = {
    "1": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Living Room Bulb",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "ct": 382,
            "effect": "none",
            "hue": 14665,
            "on": True,
            "reachable": True,
            "sat": 156,
            "xy": [0.4677, 0.4121],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:d1:fd:53-0b",
    },
    "10": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Porch 4",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 500,
            "effect": "none",
            "hue": 11004,
            "on": False,
            "reachable": True,
            "sat": 252,
            "xy": [0.5593, 0.406],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:ec:74:ab-0b",
    },
    "11": {
        "manufacturername": "Philips",
        "modelid": "LST002",
        "name": "Living Room light strips",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "ct": 389,
            "effect": "none",
            "hue": 64967,
            "on": True,
            "reachable": True,
            "sat": 79,
            "xy": [0.472, 0.353],
        },
        "swversion": "5.50.2.19072",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:01:1a:22:cd-0b",
    },
    "12": {
        "manufacturername": "Philips",
        "modelid": "LCT007",
        "name": "Arwen Dresser",
        "state": {
            "alert": "none",
            "bri": 251,
            "colormode": "xy",
            "ct": 403,
            "effect": "none",
            "hue": 14314,
            "on": False,
            "reachable": True,
            "sat": 172,
            "xy": [0.4791, 0.4139],
        },
        "swversion": "5.50.1.19085",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:10:47:9a:fe-0b",
    },
    "13": {
        "manufacturername": "Philips",
        "modelid": "LCT007",
        "name": "Arwen Changing Table",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 488,
            "effect": "none",
            "hue": 12713,
            "on": False,
            "reachable": True,
            "sat": 222,
            "xy": [0.5224, 0.414],
        },
        "swversion": "5.50.1.19085",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:10:31:ee:f0-0b",
    },
    "2": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Bedroom Susan",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 153,
            "effect": "none",
            "hue": 52067,
            "on": False,
            "reachable": True,
            "sat": 237,
            "xy": [0.3089, 0.1334],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:f9:02:ae-0b",
    },
    "3": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Bedroom Sean",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 153,
            "effect": "none",
            "hue": 52067,
            "on": False,
            "reachable": True,
            "sat": 237,
            "xy": [0.3089, 0.1334],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:fe:00:e3-0b",
    },
    "4": {
        "manufacturername": "Philips",
        "modelid": "LLC010",
        "name": "Living Room Iris",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "effect": "none",
            "hue": 58619,
            "on": True,
            "reachable": True,
            "sat": 81,
            "xy": [0.4715, 0.3499],
        },
        "swversion": "5.23.1.13452",
        "type": "Color light",
        "uniqueid": "00:17:88:01:00:12:01:83-0b",
    },
    "5": {
        "manufacturername": "Philips",
        "modelid": "LST001",
        "name": "Living Room Dim Strip",
        "state": {
            "alert": "none",
            "bri": 254,
            "colormode": "xy",
            "effect": "none",
            "hue": 58619,
            "on": True,
            "reachable": True,
            "sat": 81,
            "xy": [0.4715, 0.3499],
        },
        "swversion": "5.23.1.13452",
        "type": "Color light",
        "uniqueid": "00:17:88:01:00:cd:b2:03-0b",
    },
    "6": {
        "manufacturername": "Philips",
        "modelid": "LLC011",
        "name": "Arwen Flower",
        "state": {
            "alert": "none",
            "bri": 3,
            "colormode": "xy",
            "effect": "none",
            "hue": 64654,
            "on": True,
            "reachable": True,
            "sat": 249,
            "xy": [0.6855, 0.2927],
        },
        "swversion": "5.23.1.13452",
        "type": "Color light",
        "uniqueid": "00:17:88:01:00:c5:23:7e-0b",
    },
    "7": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Porch Fan 1",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 500,
            "effect": "none",
            "hue": 11004,
            "on": False,
            "reachable": True,
            "sat": 252,
            "xy": [0.5593, 0.406],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:fe:8a:df-0b",
    },
    "8": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Porch Fan 2",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 500,
            "effect": "none",
            "hue": 11004,
            "on": False,
            "reachable": True,
            "sat": 252,
            "xy": [0.5593, 0.406],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:f9:88:37-0b",
    },
    "9": {
        "manufacturername": "Philips",
        "modelid": "LCT001",
        "name": "Porch 3",
        "state": {
            "alert": "none",
            "bri": 117,
            "colormode": "xy",
            "ct": 500,
            "effect": "none",
            "hue": 11004,
            "on": False,
            "reachable": True,
            "sat": 252,
            "xy": [0.5593, 0.406],
        },
        "swversion": "5.23.1.13452",
        "type": "Extended color light",
        "uniqueid": "00:17:88:01:00:fe:88:17-0b",
    },
}

RESP: dict[str, dict[str, Any]] = dict(
    GET=dict(), POST=dict(), PUT=dict(), DELETE=dict()
)
RESP["GET"]["/api/username/lights/"] = LIGHTS1
for key, value in LIGHTS1.items():
    RESP["GET"][f"/api/username/lights/{key}"] = LIGHTS1[key]
