name: Tests

on:
  push:
    branches: [ master ]
    paths:
      - "src/**"
      - "python/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/test.yml"
  pull_request:
    branches: [ master ]
    paths:
      - "src/**"
      - "python/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/test.yml"

env:
  # Enable colored output
  PY_COLORS: 1

jobs:
  test:
    name: ${{ matrix.os }} - python:${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.10", "3.13"]
        include:
          - os: windows-latest
            python-version: "3.10"

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "0.6.11"
          python-version: ${{ matrix.python-version }}

      - name: Install just
        uses: extractions/setup-just@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: uv sync

      - name: Build 
        run: just build

      - name: Run tests
        run: just test